version: '3.9'

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: "$DB_USER"
      POSTGRES_PASSWORD: "$DB_PASSWORD"
    ports:
      - "$DB_PORT:5432"
    healthcheck:
        test: ["CMD-SHELL", "pg_isready -U $DB_USER"]
        interval: 5s
        timeout: 2s
        retries: 5
  
  app:
    image: kitten
    environment:
       - DATABASE_URL=postgres://$DB_USER:$DB_PASSWORD@$DB_HOST:$DB_PORT/$DB_NAME
    ports:
       - "$APP_PORT:1234"    
    depends_on:
      db:
        condition: service_healthy
    command: ["./setup.sh"]      